image: inovex/gitlab-ci-android


before_script:
  - chmod +x ./gradlew
  - echo $LOCAL_PROPERTIES > ./local.properties

variables:
  ANDROID_COMPILE_SDK: "33"
  ANDROID_BUILD_TOOLS: "33.0.0"

stages:
  - build

buildDebug:
  stage: build
  only:
    refs:
      - api
      - web
      - triggers
      - schedules
      - merge_requests
      - /v([0-9]+)-release/

  script:

    # ----- Build -----
    - ./gradlew --build-cache --gradle-user-home cache/ -Dorg.gradle.jvmargs=-Xmx8g :app:bundleDebug -Ptest_code="$CI_PIPELINE_ID"
