image: jangrewe/gitlab-ci-android


before_script:
  - chmod +x ./gradlew
  - cat $LOCAL_PROPERTIES > local.properties
  - cat $KEYSTORE_RELEASE > keystore.properties
  - export GRADLE_USER_HOME=$(pwd)/.gradle

variables:
  ANDROID_COMPILE_SDK: "33"
  ANDROID_BUILD_TOOLS: "33.0.0"

stages:
  - build

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

buildDebug:
  stage: build
  interruptible: true

  artifacts:
    paths:
      - app/build/outputs/

  only:
    refs:
      - merge_requests
      - /v([0-9]+)-release/

  script:
    - ./gradlew -Dorg.gradle.jvmargs=-Xmx16g --build-cache :app:bundleDebug
