image: inovex/gitlab-ci-android


before_script:
  - export GRADLE_USER_HOME=cache/.gradle
  - chmod +x ./gradlew

variables:
  ANDROID_COMPILE_SDK: "33"
  ANDROID_BUILD_TOOLS: "33.0.0"

stages:
  - build

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - cache/wrapper
    - cache/caches

buildDebug:
  stage: build
  only:
    refs:
      - api
      - web
      - triggers
      - schedules
      - merge_requests
      - /v([0-9]+)-release/

  script:

    # ----- Build -----
    - ./gradlew --build-cache --gradle-user-home cache/ -Dorg.gradle.jvmargs=-Xmx8g :app:bundleDebug -Ptest_code="$CI_PIPELINE_ID"
