
before_script:
  - curl -sL firebase.tools | sed 's/sudo //g' | bash
  - firebase projects:list



stages:
  - build

buildDebug:
  stage: build
  only:
    refs:
      - api
      - web
      - triggers
      - schedules
      - merge_requests
      - /v([0-9]+)-release/

  script:

    # ----- Build -----
    - firebase init
